name: Java CI

on:
  push:
    branches: [ "KhanbanTasks" ]  # Replace "dev" with your branch name
  pull_request:
    branches: [ "KhanbanTasks" ]  # Replace "dev" with your branch name
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '22.0.2'  # Set to your Java version

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and Test
      run: mvn clean test
